library(shiny)
library(shinyjs)
library(dplyr)
library(ggplot2)
library(fmsb)
library(GGally)
library(viridis)
library(hrbrthemes)
library(plotly)
library(DT)

# Source individual page files
source("pages/home.R")
source("pages/page0.R")
source("pages/page1.R")
source("pages/page2.R")
source("pages/page3.R")
